apiVersion: ENC[AES256_GCM,data:DEQ=,iv:pWDiO6NIOk2y9PV6wRgjcrRmBkwFGHwlzUTOYj5AHY0=,tag:MfCd7DwqL6T3W/5mH4VSuQ==,type:str]
kind: ENC[AES256_GCM,data:wBqGXJMW,iv:bFqDwXXifnFFwKulUj4WZmfAfqiRp0nLi56cxmSXi9U=,tag:cAnBOvAKvCx0XwTSRbe2ug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ymAOyo84YYXGqsQ/ZpAXZ9mprw==,iv:n07A3MYHAHhijxjaEsj6neZzGsIQwMCyZL/GR6Neyms=,tag:d1nN04PMlUMdkrbFQdPCjQ==,type:str]
    namespace: ENC[AES256_GCM,data:yeBZWkI=,iv:XvUzWs6m6/7LY29bwOmCojOKOPUaDuNSkCG3hk+Uqz8=,tag:CPbM9vYYpduAHadHt8CDdg==,type:str]
type: ENC[AES256_GCM,data:ZsW2BETN,iv:9sFmbYLl4Lvn0iIgV/WvUdXNaHBZA7a43PvICNQzWxo=,tag:L+6BvNTXjf9w5r7ggSBjMQ==,type:str]
stringData:
    mysql-root-password: ENC[AES256_GCM,data:K+c7E5157mARrddk9/ta,iv:IJ0x/Rgp8ja5XRZYuX46ZZnz22IXDrLotJ8LyYyulqY=,tag:u0DgsAQiopkK000knpoS+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17jj3qrr0yje37k9cvp8fmrdr9z779yjqnecync65s3g82rca0y5s9tewwf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveG11YW1NK3dqSVBDZ2VG
            aXhlZFdQUE5qbEpuUTdBREoydlJ3YitzZ1dFClF1aXdmVWZEd3pjMUZ6YkxZdzRK
            ejVLamtpUWxRRlVFTmM1WU9mK2V2T3MKLS0tIHJoS3lNOU1rL1cwZUVlcmt3T1c3
            K0Y3dml2YUlIRTlSRGl3SStTZ0RUTkUKrJCrhHgWwceS3FUQDBqJhPkRxphJFRKR
            w+4fcXFSPqi4A/3sxXVUmAoVyG3BJgmO9/3MjZvjyv05N6SNQUmZsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T07:15:47Z"
    mac: ENC[AES256_GCM,data:JPFg9olxT9wTZWO9n+RMMcEt4aVvpkpgbQAzJ2ZRZ8GwFWmEQ/Y0p31snCYMAzt/ComHMRWiVY9JbQWYqcAR3SIC7vs9y8HxFoJ2VRmzBzkC3QjxKKfoqsviG3GeuxgfHflQJrCAbEpbfWj/H8GyPkdk3NAaYXj8RQCf5cWmmZk=,iv:aPtGNdCHjhCuAGVO4+qCZX7u2Ye2Amj9SKPE+nLuRPs=,tag:sbGHA69Rxx1VvyyiUQk6FQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
